// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9CXrGVu6q5Kiy395hfhF7EmsGGJmiOZ4',
    appId: '1:354062299636:web:3f078e1dd849874c1e09a1',
    messagingSenderId: '354062299636',
    projectId: 'ecommerceapp-5eb53',
    authDomain: 'ecommerceapp-5eb53.firebaseapp.com',
    storageBucket: 'ecommerceapp-5eb53.appspot.com',
    measurementId: 'G-Z1EY9NQ9Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYgZ32u111sqHaUOasJpg4i1XIyAUnHVc',
    appId: '1:354062299636:android:44670562219d82571e09a1',
    messagingSenderId: '354062299636',
    projectId: 'ecommerceapp-5eb53',
    storageBucket: 'ecommerceapp-5eb53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw_q2_ateCxp86ltjjh5QJln5fgAWa92I',
    appId: '1:354062299636:ios:e00f99f4cb8c00ec1e09a1',
    messagingSenderId: '354062299636',
    projectId: 'ecommerceapp-5eb53',
    storageBucket: 'ecommerceapp-5eb53.appspot.com',
    iosClientId: '354062299636-3eabv0u8em032e9ot1heirrk0gf2tbc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw_q2_ateCxp86ltjjh5QJln5fgAWa92I',
    appId: '1:354062299636:ios:5624ad5dbc2690c01e09a1',
    messagingSenderId: '354062299636',
    projectId: 'ecommerceapp-5eb53',
    storageBucket: 'ecommerceapp-5eb53.appspot.com',
    iosClientId: '354062299636-h1cb0q8th9iq9d28skd1amv2e8r9ichq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceVendor.RunnerTests',
  );
}
